//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameUser
    {
        public long UserID { get; set; }
        public long GameID { get; set; }
        public long Position { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
